version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    networks:
      - aether-net

  gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - aether-net

  redis:
    image: redis:7.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - aether-net

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: aether_admin
      POSTGRES_PASSWORD: aether_ultra_secret
      POSTGRES_DB: aether_vault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aether-net

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - aether-net

networks:
  aether-net:
    driver: bridge

volumes:
  qdrant_data:
  postgres_data:
